//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1Progra3QUIZ.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTO
    {
        public int ID { get; set; }
        public string TipoDocumento { get; set; }
        public string NumeroDocumento { get; set; }
        public System.DateTime FechaExpiracion { get; set; }
        public int EstadoID { get; set; }
        public int IdViajero { get; set; }
    
        public virtual ESTADOS ESTADOS { get; set; }
        public virtual VIAJEROS VIAJEROS { get; set; }
    }
}
