//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1Progra3QUIZ.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIMIENTOS
    {
        public int ID { get; set; }
        public int IdViajero { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Destino { get; set; }
        public string Origen { get; set; }
        public string TipoSolicitud { get; set; }
        public int IdUsuario { get; set; }
    
        public virtual USUARIOS USUARIOS { get; set; }
        public virtual VIAJEROS VIAJEROS { get; set; }
    }
}
